---
- name: Install postgres client
  yum:
    name: postgresql
    state: present
  tags:
    - setup_node
    - setup_postgres
    - cluster_setup

- name: Create Postgres group
  group: name=postgres state=present
  tags:
    - setup_node
    - setup_postgres
    - cluster_setup

- name: Create Postgres user
  user: name=postgres state=present group=postgres
  tags:
    - setup_node
    - setup_postgres
    - cluster_setup

- name: Create Postgres data directory
  file:
    path: "{{ postgres_mount_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
  - setup_node
  - setup_postgres
  - cluster_setup
