---
- name: Check if postgres port is free
  shell: lsof -i:{{ postgres_port }} -t
  args:
    executable: /bin/bash
  ignore_errors: yes
  changed_when: false
  register: postgres_status
  tags:
    - start_postgres
    - check_postgres
    - start
    - check
    - cluster_setup
    - setup_postgres

- name: Start Postgres container
  docker_container:
    name: "{{ postgres_container_name }}"
    image: "{{ postgres_docker_image }}"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - "{{ postgres_mount_data_dir }}:{{ postgres_data_dir }}"
    state: started
    restart_policy: always
    ports:
      - "{{ postgres_port }}:5432"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
  vars:
    ansible_python_interpreter: "{{ docker_python_interpreter }}"
  when: postgres_status.rc == 1
  tags:
    - start_postgres
    - start
    - cluster_setup
    - setup_postgres

- name: Stop Postgres container
  docker_container:
    name: "{{ postgres_container_name }}"
    state: stopped
  vars:
    ansible_python_interpreter: "{{ docker_python_interpreter }}"
  tags:
    - stop_postgres
    - stop
    - never
