- name: Install Java
  yum: 
    name: "{{jdk_download_url}}"
    state: present
  tags:
    - setup_node
    - cluster_setup

- name: Creating Java Env file
  template:
    src: files/java.sh
    dest: /etc/profile.d/java.sh
    force: yes
    mode: 0665
  tags:
    - setup_node
    - cluster_setup 

