- name: copy zeppelin-env.sh file 
  template: 
    src: files/zeppelin-env.sh
    dest: /opt/zeppelin/conf/zeppelin-env.sh
    owner: zeppelin
    group: zeppelin
    mode: 0755
  tags:
    - setup_node
    - setup_zeppelin
    - configure_zeppelin
    - cluster_setup

- name: copy zeppelin-site.xml file
  template: 
    src: files/zeppelin-site.xml
    dest: /opt/zeppelin/conf/zeppelin-site.xml
    owner: zeppelin
    group: zeppelin
    mode: 0755
  tags:
    - setup_node
    - setup_zeppelin
    - configure_zeppelin
    - cluster_setup

- name: Copying zeppelin systemd service file
  template:
    src: files/zeppelin.service
    dest: /etc/systemd/system/zeppelin.service
  tags:
    - setup_node
    - setup_zeppelin
    - configure_zeppelin
    - cluster_setup
