---
postgres_mount_data_dir: /data/1/postgres_data
postgres_data_dir: /var/lib/postgresql/data
postgres_password: postgres
postgres_port: 5432
postgres_container_name: postgres-12
postgres_docker_image: postgres:12
postgres_exporter_container_name: postgres_exporter
postgres_exporter_docker_image: wrouesnel/postgres_exporter
postgres_exporter_port: 9187
postgres_data_source_name: postgresql://postgres:{{postgres_password}}@{{ansible_default_ipv4.address}}:{{postgres_port}}/?sslmode=disable
pgadmin_data_dir: /var/lib/pgadmin4/data
pgadmin_mount_data_dir: /data/1/pgadmin_data
pgadmin_port: 5080
pgadmin_container_name: pgadmin4
pgadmin_image_name: dpage/pgadmin4:6.10
pgadmin_default_emailid: pgadmin@argoid.com
pgadmin_default_password: Argoid2020
