- name: install yum-utils
  yum:
    name: 
      - epel-release
      - yum-utils
    state: present
  tags:
    - setup_nginx
    - setup_node
    - cluster_setup

- name: Install nginx
  yum:
    name:
      - nginx
      - certbot
    state: present
  tags:
    - setup_nginx
    - setup_node
    - cluster_setup

- name: Disable SELinux
  selinux: state=disabled
  tags:
  - setup_nginx
  - setup_node
  - cluster_setup
