---
- name: get cluster facts
  hosts: all
  tasks: []

- hosts: argoid
  remote_user: manjunath
  gather_facts: true
  become: yes
  vars:
    ansible_ssh_private_key_file: "roles/argoid-user/files/id_rsa"
  roles:
    - roles/argoid-user

- hosts: argoid_ott
  remote_user: argoid
  gather_facts: true
  become: yes
  vars:
    ansible_ssh_private_key_file: "roles/argoid-user/files/id_rsa"
  roles:
    - roles/common

- hosts: docker
  remote_user: argoid_ansible_user
  gather_facts: true
  become: yes
  vars:
    ansible_ssh_private_key_file: "roles/argoid-user/files/id_rsa"
  roles:
    - roles/common
