---
# tasks file for airflow
 - import_tasks: install.yml
 - import_tasks: configure.yml
 - import_tasks: service.yml
 - import_tasks: statsd-exporter.yml
   when: airflow_enable_statsd_monitoring  == True

