groups:
- name: haproxy-prod.rules
  rules:
  - alert: SaaS-Prod1(RR) CRITICAL HA Proxy Metric exporter or HAProxy is down on 10.0.0.23
    expr: up{job="haproxy_100023"} == 0
    for: 2m
    labels:
      severity: "critical"
    annotations:
      summary: "HA Proxy Metric exprter from  10.0.0.23 is down; Grafana URL http://10.0.0.15:3000/d/353BLLPMl/haproxy?orgId=1&refresh=5m&from=now-1h&to=now&var-host=10.0.0.23&var-port=9101&var-backend=All&var-frontend=All&var-server=All&var-code=All&var-interval=30s"


  - alert: SaaS-Prod1(RR) CRITICAL HAProxy is Down on 10.0.0.23
    expr:  haproxy_up{job="haproxy_100023"} == 0
    for: 2m
    labels:
      severity: "critical"
    annotations:
      summary: "HA Proxy server is down; Grafana URL http://10.0.0.15:3000/d/353BLLPMl/haproxy?orgId=1&refresh=5m&from=now-1h&to=now&var-host=10.0.0.23&var-port=9101&var-backend=All&var-frontend=All&var-server=All&var-code=All&var-interval=30s"

  - alert: SaaS-Prod1(RR) CRITICAL HAProxy Backend are down 
    expr:  haproxy_backend_up{job="haproxy_100023",backend="http_back"} == 0
    for: 2m
    labels:
      severity: "critical"
    annotations:
      summary: "Grafana URL http://10.0.0.15:3000/d/353BLLPMl/haproxy?orgId=1&refresh=5m&from=now-1h&to=now&var-host=10.0.0.23&var-port=9101&var-backend=All&var-frontend=All&var-server=All&var-code=All&var-interval=30s"
      description: " Refer this Runbook , "


  - alert: SaaS-Prod1(RR) WARNING HAProxy Receiving More 4xx Error codes
    expr: ((sum by (server) (rate(haproxy_server_http_responses_total{code="4xx",backend="http_back",job="haproxy_100023"}[1m])) / sum by (server) (rate(haproxy_server_http_responses_total{backend="http_back",job="haproxy_100023"}[1m]))) * 100)  > 3
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: HAProxy high HTTP 4xx error rate backend (instance {{ $labels.instance }})
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=12&fullscreen&orgId=1&from=now-12h&to=now "


  - alert: SaaS-Prod1(RR) WARNING HAProxy Receiving More 5xx Error codes
    expr: ((sum by (server) (rate(haproxy_server_http_responses_total{code="5xx",backend="http_back",job="haproxy_100023"}[1m])) / sum by (server) (rate(haproxy_server_http_responses_total{backend="http_back",job="haproxy_100023"}[1m]))) * 100)   > 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: HAProxy high HTTP 4xx error rate backend (instance {{ $labels.instance }})
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=14&fullscreen&orgId=1&from=now-12h&to=now"


  - alert: SaaS-Prod1(RR) WARNING HAProxy Server-Response-Errors
    expr: (sum by (server) (rate(haproxy_server_response_errors_total{backend="http_back",job="haproxy_100023"}[1m])) / sum by (server) (rate(haproxy_server_http_responses_total{backend="http_back",job="haproxy_100023"}[1m]))) * 100  > 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: HAProxy server response errors (instance {{ $labels.instance }})
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=16&edit&fullscreen&orgId=1&from=now-12h&to=now"

  - alert: SaaS-Prod1(RR) WARNING HAProxy HaproxyBackendConnectionErrors
    expr: rate(haproxy_backend_connection_errors_total{backend="http_back",job="haproxy_100023"}[1m])* 100  > 2
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: HAProxy backend connection errors (instance {{ $labels.instance }})
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=18&fullscreen&orgId=1&from=now-12h&to=now"

  - alert: SaaS-Prod1(RR) WARNING HAProxy HaproxyPendingRequests
    expr: haproxy_backend_current_queue{backend="http_back",job="haproxy_100023"}  > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: HAProxy pending requests (instance {{ $labels.instance }})
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=22&fullscreen&orgId=1&from=now-12h&to=now "


  - alert: SaaS-Prod1(RR) WARNING HAProxy HaproxyServerConnectionErrors
    expr: rate(haproxy_server_connection_errors_total{backend="http_back",job="haproxy_100023"}[1m])  > 2
    for: 0m
    labels:
      severity: warning 
    annotations:
      summary: HAProxy server connection errors (instance {{ $labels.instance }})
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=20&fullscreen&orgId=1&from=now-12h&to=now"


  - alert: SaaS-Prod1(RR) WARNING HAProxy-Reco-Rest  High Latency  
    expr: haproxy_backend_http_total_time_average_seconds{job="haproxy_100023", backend="http_back"} > 5
    for: 2m
    labels:
      severity: warning
    annotations:
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=4&fullscreen&orgId=1&from=now-3h&to=now"


  - alert: SaaS-Prod1(AZ) WARNING HAProxy HaproxyServerConnectionErrors
    expr: rate(haproxy_server_connection_errors_total{backend="http_back",job="haproxy_100047"}[1m])  > 2
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: HAProxy server connection errors (instance {{ $labels.instance }})
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=20&fullscreen&orgId=1&from=now-12h&to=now"


  - alert: SaaS-Prod1(AZ) WARNING HAProxy-Reco-Rest  High Latency
    expr: haproxy_backend_http_total_time_average_seconds{job="haproxy_100047", backend="http_back"} > 5
    for: 2m
    labels:
      severity: warning
    annotations:
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=4&fullscreen&orgId=1&from=now-3h&to=now"



  - alert: SaaS-Prod1(Fun2) WARNING HAProxy HaproxyServerConnectionErrors
    expr: rate(haproxy_server_connection_errors_total{backend="http_back",job="haproxy_100052"}[1m])  > 2
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: HAProxy server connection errors (instance {{ $labels.instance }})
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=20&fullscreen&orgId=1&from=now-12h&to=now"


  - alert: SaaS-Prod1(Fun2) WARNING HAProxy-Reco-Rest  High Latency
    expr: haproxy_backend_http_total_time_average_seconds{job="haproxy_100052", backend="http_back"} > 5
    for: 2m
    labels:
      severity: warning
    annotations:
      description: "Grafana URL http://10.0.0.15:3000/d/OonW07jjg/haproxy-reco-backend-alerts?panelId=4&fullscreen&orgId=1&from=now-3h&to=now"
