groups:
- name: hdfs-datanode.rules
  rules:
  - alert: SaaS-Prod1(Common) WARNING HDFS Datanode  heap usage is high
    expr: sum by (instance)(avg_over_time(Hadoop_DataNode_MemHeapUsedM[1m]))/ sum by (instance)(avg_over_time(Hadoop_DataNode_MemHeapMaxM[1m]))  >= 0.8
    for: 2m
    labels:
      severity: "Warning"
    annotations:
      summary: "Heap Usage from DataNode  {{$labels.instance}} is high; Grafana URL http://10.0.0.15:3000/d/e6WoHpZWl/hdfs?orgId=1"

  - alert: SaaS-Prod1(Common) CRITICAL HDFS Datanode heap usage is high
    expr: sum by (instance)(avg_over_time(Hadoop_DataNode_MemHeapUsedM[1m]))/ sum by (instance)(avg_over_time(Hadoop_DataNode_MemHeapMaxM[1m]))  >= 0.9
    for: 2m
    labels:
      severity: "Critical"
    annotations:
      summary: "Heap Usage from DataNode  {{$labels.instance}} is high; Grafana URL http://10.0.0.15:3000/d/e6WoHpZWl/hdfs?orgId=1"

  - alert: SaaS-Prod1(Common) CRITICAL HDFS Datanode is Down
    expr:  up{job=~"datanode_.*"} == 0
    for: 2m
    labels:
      severity: "critical"
    annotations:
      summary: "Grafana URL http://10.0.0.15:3000/d/e6WoHpZWl/hdfs?orgId=1"
