---
- name: Start Mysql
  systemd:
    state: started
    name: mysqld
  tags:
  - start_mysql
  - start
  - cluster_setup
  - setup_node

- name: Stop Mysql
  systemd:
    state: stopped
    name: mysqld
  tags:
  - stop_mysql
  - stop
