---
airflow_dir: /home/airflow/airflow
airflow_user: airflow
airflow_dags_dir: /opt/airflow/dags
airflow_executor: SequentialExecutor
plugins_folder: /home/airflow/airflow/plugins
dag_processor_manager_log_location: /home/airflow/airflow/logs/dag_processor_manager/dag_processor_manager.log
child_process_log_directory: /home/airflow/airflow/logs/scheduler
base_log_folder: /home/airflow/airflow/logs
python3_virtualenv_path:  /opt/python3_venv
python_bin_path: /opt/python3_venv/bin/python
python_bin_path_airflow: /opt/python3_venv/bin/airflow
##airflow postgres database user and password creation
airflow_packages: [ "SQLAlchemy==1.3.20","apache-airflow[postgres]==2.0.1", "apache-airflow[statsd]", "apache-airflow[cncf.kubernetes]" ]
airflow_postgres_db: airflow
airflow_postgres_user: airflow
airflow_postgres_password: airflow
####statsd_monitoring paths
statsd_exporter_port: 9102
statsd_exporter_docker_image: prom/statsd-exporter
statsd_exporter_container_name: airflow-statsd-exporter
airflow_statsd_port: 9125
####airflow new web user creation(admin role)
airflow_web_user_id: admin
airflow_web_user_first_name: argoid
airflow_web_user_last_name: admin
airflow_web_user_password: argoid
airflow_web_user_role: Admin
airflow_web_user_email: argoid@argoid.com
####logrotation airflow_logs
cron_log_rotation_minutes_utc: 30
cron_log_rotation_hour_utc: 05
log_to_zip_no_of_days: 3
zip_to_delete_no_of_days: 7
###systemd script inairflow
environmentfile: /etc/sysconfig/airflow
