---
- hosts: cassandra 
  remote_user: argoid 
#"{{ cassandra_user }}"
  gather_facts: true
  become: yes
  vars:
    ansible_ssh_private_key_file: "roles/ansible-ssh-user/files/id_rsa"
  roles:
    - roles/cassandra
