---
- hosts: python3_venv
  remote_user: argoid
  gather_facts: true
  become: yes
  vars:
    ansible_ssh_private_key_file: "roles/ansible-ssh-user/files/id_rsa"
  roles:
    - roles/python3-virtualenv
