  - name: Check if pip is installed or not
    stat:
      path: "{{ pip_bin_location }}"
    register: pip_installed
    tags:
    - setup_node
    - setup_pip  
    - setup_pip_venv  

  - name: Download pip installer
    get_url:
      url: "{{ pip_download_url }}"
      dest: /tmp/get-pip.py
    when: pip_installed.stat.exists == False
    tags:
    - setup_node
    - setup_pip  
    - setup_pip_venv  

  - name: Install pip
    shell: "{{ python2_bin_path }} /tmp/get-pip.py"
    when: pip_installed.stat.exists == False
    tags:
    - setup_node
    - setup_pip
    - setup_pip_venv  

  - name: Install virtualenv module
    pip:
      name: virtualenv
    tags:
    - setup_node
    - setup_venv
    - setup_pip_venv

  - name: Delete get-pip.py file
    file:
      path: /tmp/get-pip.py
      state: absent
    ignore_errors: True
    tags:
    - setup_node
    - setup_venv
    - setup_pip_venv
