---
# tasks file for hadoop
- import_tasks: install.yml

- import_tasks: data-dir.yml

- import_tasks: configure.yml

- import_tasks: bootstrap_standalone.yml
  when: hdfs_bootstrap == True  and not hdfs_ha_enabled

- import_tasks: bootstrap_ha.yml
  when: hdfs_bootstrap == True and hdfs_ha_enabled

- import_tasks: service_start.yml
- import_tasks: post-setup.yml 

- import_tasks: graceful_stop.yml

- import_tasks: service_restart.yml
