---
- name: Install HDFS Client
  yum:
    name: hadoop-hdfs.x86_64
    state: present
  tags:
  - setup_yarn
  - setup_nodemanager
  - setup_hadoop_client
  - setup_spark_client

- name: Install ResourceManager
  yum:
    name: hadoop-yarn-resourcemanager.x86_64
    state: present
  when:
    - inventory_hostname in  "{{ groups.yarn_resourcemanager }}"
  tags:
  - setup_yarn

- name: Install NodeManager
  yum:
    name:
      - hadoop-yarn-nodemanager.x86_64
      - hadoop-mapreduce.x86_64
    state: present
  when:
    - inventory_hostname in  "{{ groups.yarn_nodemanager }}"
  tags:
  - setup_nodemanager
  - setup_yarn

- name: Install Hadoop Client Packages
  yum:
    name:
      - hadoop-client.x86_64
      - hadoop-hdfs.x86_64
      - hadoop-yarn.x86_64
      - hadoop-libhdfs-devel.x86_64
    state: present
  when:
    - inventory_hostname in  "{{ groups.hadoop_clients }}"
  tags:
  - setup_nodemanager
  - setup_yarn
  - setup_hadoop_client
  - setup_spark_client
