---
- name: Create Alertmanager group
  group: name=alertmanager state=present
  tags:
    - setup_node 
    - cluster_setup
    - setup_alertmanager

- name: Create Alertmanager user
  user: name=alertmanager state=present group=alertmanager
  tags:
    - setup_node 
    - cluster_setup
    - setup_alertmanager

- name: Create Alertmanager data directory
  file:
    path: "{{ alertmanager_mount_data_dir }}"
    state: directory
    owner: alertmanager 
    group: alertmanager
    mode: 0755
  tags:
  - setup_node 
  - cluster_setup
  - setup_alertmanager
