- name: Check if node_exporter_port is free
  shell: lsof -i:{{ node_exporter_port }} -t
  args:
    executable: /bin/bash
  ignore_errors: yes
  changed_when: false
  register: node_exporter_status
  tags:
    - check_node_exporter
    - check

- name: Start node_exporter
  service:
    name: node_exporter
    state: started
    daemon_reload: yes
  tags:
    - start
    - start_node_exporter

- name: Stop node_exporter
  service:
    name: node_exporter
    state: stopped
  tags:
    - stop_node_exporter
